const fakeDepartmentData = [
  { department_id: 'DP001', name: 'Phòng Nhân Sự', description: 'Quản lý nhân sự & tuyển dụng' },
  { department_id: 'DP002', name: 'Phòng Kế Toán', description: 'Theo dõi sổ sách & tài chính' },
  { department_id: 'DP003', name: 'Phòng IT', description: 'Phát triển & vận hành hệ thống' },
  { department_id: 'DP004', name: 'Phòng Marketing', description: 'Truyền thông & quảng cáo' },
  { department_id: 'DP005', name: 'Phòng Sales', description: 'Bán hàng & chăm sóc khách hàng' },
  { department_id: 'DP006', name: 'Phòng Pháp Chế', description: 'Xử lý vấn đề pháp lý' },
  { department_id: 'DP007', name: 'Phòng Vận Hành', description: 'Quản lý hoạt động doanh nghiệp' },
  { department_id: 'DP008', name: 'Phòng Kho Vận', description: 'Quản lý kho & logistics' },
  { department_id: 'DP009', name: 'Phòng R&D', description: 'Nghiên cứu & phát triển sản phẩm' },
  { department_id: 'DP010', name: 'Phòng CSKH', description: 'Hỗ trợ khách hàng' },
]

const fakeJobPositionData = [
  {
    job_position_id: 'JP001',
    name: 'Junior Developer',
    description: 'Phát triển tính năng cơ bản',
    level: 'Junior',
    min_salary: 800,
    max_salary: 1200,
    is_active: true,
  },
  {
    job_position_id: 'JP002',
    name: 'Senior Developer',
    description: 'Thiết kế kiến trúc & review code',
    level: 'Senior',
    min_salary: 1500,
    max_salary: 2200,
    is_active: true,
  },
  {
    job_position_id: 'JP003',
    name: 'Team Lead',
    description: 'Quản lý team dev',
    level: 'Lead',
    min_salary: 2000,
    max_salary: 2800,
    is_active: true,
  },
  {
    job_position_id: 'JP004',
    name: 'HR Specialist',
    description: 'Tuyển dụng & đào tạo',
    level: 'Mid',
    min_salary: 900,
    max_salary: 1500,
    is_active: true,
  },
  {
    job_position_id: 'JP005',
    name: 'Accountant',
    description: 'Quản lý tài chính & sổ sách',
    level: 'Mid',
    min_salary: 1000,
    max_salary: 1600,
    is_active: false,
  },
  {
    job_position_id: 'JP006',
    name: 'Marketing Executive',
    description: 'Thực hiện chiến dịch marketing',
    level: 'Junior',
    min_salary: 700,
    max_salary: 1100,
    is_active: true,
  },
  {
    job_position_id: 'JP007',
    name: 'Sales Manager',
    description: 'Quản lý đội Sales',
    level: 'Manager',
    min_salary: 1800,
    max_salary: 3000,
    is_active: true,
  },
  {
    job_position_id: 'JP008',
    name: 'Product Manager',
    description: 'Xây dựng roadmap sản phẩm',
    level: 'Senior',
    min_salary: 2000,
    max_salary: 3500,
    is_active: false,
  },
  {
    job_position_id: 'JP009',
    name: 'UI/UX Designer',
    description: 'Thiết kế trải nghiệm người dùng',
    level: 'Mid',
    min_salary: 900,
    max_salary: 1600,
    is_active: true,
  },
  {
    job_position_id: 'JP010',
    name: 'DevOps Engineer',
    description: 'Triển khai & tối ưu hệ thống',
    level: 'Senior',
    min_salary: 1700,
    max_salary: 2500,
    is_active: true,
  },
]

export { fakeDepartmentData, fakeJobPositionData }
